title: "MoP4 - pipeline"
subtitle: ""
intro_text: False

report_header_info:
    - Please cite: "Cozzuto L, Liu H, Pryszcz LP, Pulido TH, Delgado-Tejedor A, Ponomarenko J, Novoa EM. MasterOfPores: A Workflow for the Analysis of Oxford Nanopore Direct RNA Sequencing Datasets. Front Genet. 2020 Mar 17;11:211. doi: 10.3389/fgene.2020.00211"
    - And: "Cozzuto L, Delgado-Tejedor A, Hermoso Pulido T, Novoa EM, Ponomarenko J. Nanopore Direct RNA Sequencing Data Processing and Analysis Using MasterOfPores. N. Methods Mol Biol. 2023;2624:185-205. doi: 10.1007/978-1-0716-2962-8_13."

custom_logo: 'logo_small.png'
custom_logo_url: 'https://github.com/biocorecrg/MoP4'
custom_logo_title: 'Master of Pores 4'

extra_fn_clean_trim:
   - '_QC'
   - '.count'
   - '-report'
   - '_nanostat'
table_columns_visible:
    nanoq:
        number_of_bases: True

top_modules:
 - fastqc:
        name: 'FastQC'
        info: 'This section of the report shows FastQC results on raw reads.'
 - alnQC:
        name: "alnQC"
        info: 'This section of the report shows alnQC results on aligned reads'
 - minionqc
 - nanoplots:
        info: 'Nanoplot stats'
