FROM nvidia/cuda:10.1-base-ubuntu18.04 

MAINTAINER Leszek Pryszcz <l.p.pryszcz+docker@gmail.com>

ARG PORECHOP_VERSION=0.2.4

# Install Python3 & pip, curl
RUN apt update && apt install -y python3-setuptools curl
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py && rm get-pip.py

RUN mkdir -p /project
WORKDIR /project

# Install guppy & its dependencies
RUN apt update && apt install -y p7zip-full libidn11 libgssapi-krb5-2

# Installing Porechop
RUN apt update && apt install -y g++ make
RUN bash -c 'curl -k -L https://github.com/rrwick/Porechop/archive/v${PORECHOP_VERSION}.tar.gz > porechop.tar.gz'
RUN tar -zvxf porechop.tar.gz; cd Porechop-${PORECHOP_VERSION}; python setup.py install; cd ../
RUN rm -fr Porechop-0.2.4 porechop.tar.gz

# Cleanup
RUN apt-get clean && apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* 
RUN locale-gen en_US.UTF-8

ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/cuda-10.1/compat/
ENV PYTHONPATH $PATH 
WORKDIR /
