FROM biocorecrg/centos-perlbrew-pyenv3-java:centos7

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

ARG NANOCOMPORE_VERSION=v1.0.0rc3-1
ARG MEDAKA_VERSION=v0.11.5
ARG NANOPOLISHCOMP_VERSION=v0.6.2
#upgrade pip
RUN pip install -U pip
RUN pip install --upgrade setuptools

# Installing
RUN pip install nanocompore==${NANOCOMPORE_VERSION}

# Intaalling Medaka
RUN pip install medaka==${MEDAKA_VERSION}

# Installing 
RUN pip install NanopolishComp==${NANOPOLISHCOMP_VERSION}

# Clean cache
RUN yum clean all 

#cleaning
RUN rm -fr *.tar.gz; rm -fr *.bz2; rm -fr ./tmp
RUN rm -rf /var/cache/yum

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8
