# This will do biocorecrg/mopmod:0.6.1
FROM biocorecrg/centos-perlbrew-pyenv3-java:centos7

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

ARG PICARD_VERSION=2.20.0
ARG TOMBO_VERSION=1.5 
ARG SAMTOOLS_VERSION=1.4.1
ARG BEDTOOLS_VERSION=2.29.2

#upgrade pip
RUN pip install -U pip
RUN pip install --upgrade setuptools

# Installing Tombo
RUN pip install ont-fast5-api
RUN pip install pyfaidx numpy
RUN pip install ont-tombo==${TOMBO_VERSION}

# Installing samtools
RUN yum install -y xz-devel.x86_64
RUN bash -c 'curl -k -L https://downloads.sourceforge.net/project/samtools/samtools/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2 > samtools.tar.bz2'
RUN tar -jvxf samtools.tar.bz2
RUN cd samtools-${SAMTOOLS_VERSION}; ./configure; make; make install; cd ../ 
RUN rm samtools.tar.bz2

# install sam2tsv // version is last github 
RUN git clone "https://github.com/lindenb/jvarkit.git"; cd jvarkit; ./gradlew sam2tsv

# Installing Picard
RUN bash -c 'curl -k -L https://github.com/broadinstitute/picard/releases/download/${PICARD_VERSION}/picard.jar > /usr/local/bin/picard.jar'

# Installing BEDTOOLS
RUN bash -c 'curl -k -L https://github.com/arq5x/bedtools2/releases/download/v${BEDTOOLS_VERSION}/bedtools.static.binary > /usr/local/bin/bedtools'
RUN chmod +x /usr/local/bin/bedtools

RUN pip install h5py pandas pyarrow==0.12.1
RUN pip install pyBigWig

# Add wigToBigWig
RUN bash -c 'curl -k -L http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig > /usr/local/bin/wigToBigWig'
RUN chmod +x /usr/local/bin/wigToBigWig


# Clean cache
RUN yum clean all 

#cleaning
RUN rm -fr *.tar.gz; rm -fr *.bz2; rm -fr ./tmp
RUN rm -rf /var/cache/yum
RUN rm -fr fastqc.zip  samtools-* 

#plugin
RUN yum install -y wget
RUN wget https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz; tar -zvxf ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
RUN mv ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/ /usr/local/  
ENV HDF5_PLUGIN_PATH "/usr/local/hdf5/lib/plugin"
#ENV LD_LIBRARY_PATH "/usr/local/hdf5/lib/plugin"

ENV SAM2TSV "java -jar /project/jvarkit/dist/sam2tsv.jar"
ENV PICARD "java -jar /usr/local/bin/picard.jar"
ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

