FROM rocker/verse:4.2.3

RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_cran("rlang")'
RUN apt-get update && apt-get install -y libcurl4-openssl-dev libhdf5-dev libicu-dev libssl-dev make pandoc zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN Rscript -e 'remotes::install_version("rbokeh")'

RUN apt-get update && apt-get install patch
#RUN Rscript -e "remotes::install_github('adnaniazi/tailfindr', ref='master')"

RUN Rscript -e "install.packages(c('data.table','flexdashboard','dplyr','plyr','ggExtra','ggplot2','hexbin','knitr','optparse','RColorBrewer','reshape2'), repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages(c('devtools', 'futile.logger','readr','scales','viridis','yaml', 'ggplot2'), dependencies = TRUE, repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages(c('BiocManager', 'snow'), repos='http://cran.us.r-project.org')"; Rscript -e "BiocManager::install()"
RUN Rscript -e "BiocManager::install(c('BiocGenerics', 'Biostrings', 'IRanges', 'zlibbioc', 'XVector', 'bit', 'pryr'))"
RUN Rscript -e "BiocManager::install(c('hdf5r'))"
RUN Rscript -e "BiocManager::install(c('foreach', 'doParallel', 'doSNOW', 'rbokeh', 'psych', 'gistr', 'mnormt'))"
RUN Rscript -e "BiocManager::install(c('Rsamtools'))"
RUN Rscript -e "BiocManager::install(c('tidyr'))"
RUN Rscript -e "install.packages(c('remotes'), repos='http://cran.us.r-project.org')"
RUN Rscript -e 'remotes::install_version("rbokeh", repos = "http://cran.us.r-project.org")'
RUN Rscript -e "remotes::install_github(\"adnaniazi/tailfindr\", ref=\"nano3p-seq-r10\", dependencies=FALSE, INSTALL_opts=c(\"--no-docs\", \"--no-help\"))"



RUN Rscript -e "install.packages(c('argparse', 'gplots', 'VennDiagram'), dependencies = TRUE, repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages(c('ggrepel', 'MASS', 'reshape2'), repos='http://cran.us.r-project.org')"; Rscript -e "BiocManager::install()"



# Install VBZ plugin
RUN apt-get update && apt-get install -y wget
#RUN wget https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz && \
    #tar -xzf ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz -C /usr/local/
#ENV HDF5_PLUGIN_PATH "/usr/local/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin"

#RUN yum install -y hdf5-devel wget
RUN wget https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz; tar -zvxf ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
RUN mv ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/ /usr/local/
ENV HDF5_PLUGIN_PATH "/usr/local/hdf5/lib/plugin"
ENV LD_LIBRARY_PATH "/usr/local/hdf5/lib"
ENV PATH "/usr/local/hdf5/bin":${PATH}
ENV HDF5_PLUGIN_PATH "/usr/local/hdf5/lib/plugin"
ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8
