name: CI
# When this workflow is triggered
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'assets/**'
      - '.github/workflows/**'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'assets/**'
      - '.github/workflows/**'
      - 'docs/**'

jobs:
  build:
    name: mop3 ci
    # This job runs on Linux
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        java_version: [11]

    steps:
      - name: Delete huge unnecessary tools folder
        uses: jlumbroso/free-disk-space@main
        with:
         tool-cache: true

      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
         token: ${{ github.token }}
         ref: ${{ github.ref }}
         repository: biocorecrg/master_of_pores
         fetch-depth: 1
         submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
         java-version: ${{ matrix.java_version }}
         distribution: 'adopt'
         architecture: x64

      - name: MOP3
        run: |
          curl -fsSL get.nextflow.io | bash
          bash INSTALL.sh
          cd mop_preprocess
          ../nextflow run mop_preprocess.nf -params-file params.f5.yaml -with-docker -profile ci
          cd ../mop_mod
          ../nextflow run mop_mod.nf -params-file params.yaml -with-docker -profile ci
          cd ../mop_tail
           ../nextflow run mop_tail.nf -with-docker  -params-file params.yaml -profile ci

        env:
          NXF_ANSI_LOG: false
