name: mop4-CI
# When this workflow is triggered
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: mop4 ci
    # This job runs on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        java_version: [21]

    steps:
      - name: Delete huge unnecessary tools folder
        uses: jlumbroso/free-disk-space@main
        with:
         tool-cache: true

      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
         token: ${{ github.token }}
         repository: biocorecrg/master_of_pores
         fetch-depth: 1
         submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
         java-version: ${{ matrix.java_version }}
         distribution: 'adopt'
         architecture: x64

      - name: MOP4
        run: |
          curl -fsSL get.nextflow.io | bash
          cd mop_preprocess
          ../nextflow run mop_preprocess.nf -params-file params.yaml -with-docker -profile ci

        env:
          NXF_ANSI_LOG: false
          NXF_VER: 24.04.4
