name: mop4-CI
# When this workflow is triggered
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: mop4 ci
    # This job runs on Linux
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        java_version: [11]

    steps:
      - name: Delete huge unnecessary tools folder
        uses: jlumbroso/free-disk-space@main
        with:
         tool-cache: true

      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
         token: ${{ github.token }}
         repository: biocorecrg/MOP4
         fetch-depth: 1
         submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
         java-version: ${{ matrix.java_version }}
         distribution: 'adopt'
         architecture: x64

      - name: MOP4
        run: |
          curl -fsSL get.nextflow.io | bash
          cd mop_preprocess
          ../nextflow run mop_preprocess.nf -params-file params.yaml -with-docker -profile ci
         # cd ../mop_mod
         # ../nextflow run mop_mod.nf -params-file params.yaml -with-docker -profile ci
         # cd ../mop_tail
         #  ../nextflow run mop_tail.nf -with-docker  -params-file params.yaml -profile ci

        env:
          NXF_ANSI_LOG: false
