name: Docs
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        path: ${{ github.ref_name }}
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
    - name: Prepare Ruby and Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: Install ruby dependencies
      run: bundle install
    - name: Build website
      run: |
        cd ${{ github.ref_name }}/docs/ \
        && bundle exec jekyll build
    - name: Copy file
      run: |
        mkdir -p ./gh-pages/${{ github.ref_name }}/ \
        && cp -pr ${{ github.ref_name }}/docs/* ./gh-pages/${{ github.ref_name }}/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
